bind       = "unix:/nginx_sockets/fast_api_experiment.sock"
user       = "nginx"
logto      = "/var/log/uwsgi/fast_api_experiment_access.log"
errorlog   = "/var/log/uwsgi/fast_api_experiment_error.log"
root_path  = "/fast_api_experiment"